# Generated by Django 4.2.11 on 2024-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastDayOutPut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'last_day_out_put',
            },
        ),
        migrations.CreateModel(
            name='RealOEEDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'real_oeeday',
            },
        ),
    ]
