# Generated by Django 4.2.11 on 2024-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('output', '0002_alter_lastdayoutput_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastdayoutput',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
