# Generated by Django 4.2.9 on 2024-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Admin', 'Admin'), ('Principle', 'Principle'), ('Coach', 'Coach')], max_length=20, null=True),
        ),
    ]
