# Generated by Django 4.2.9 on 2024-03-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
