# Generated by Django 4.2.9 on 2024-03-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
