# Generated by Django 4.2.9 on 2024-03-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='best_score',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
